# Generated by Django 5.2.3 on 2025-06-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_usuario_bairro_usuario_cidade_usuario_complemento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='categoria',
            field=models.CharField(default='Sem categoria', max_length=100),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='fabricante',
            field=models.CharField(default='Genérico', max_length=100),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='modelo',
            field=models.CharField(default='Desconhecido', max_length=100),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='numero_serie',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('indisponivel', 'Indisponível')], default='disponivel', max_length=20),
        ),
    ]
