# Generated by Django 5.2.3 on 2025-06-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_equipamento_categoria_equipamento_fabricante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='fabricante',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
