# Generated by Django 5.2.3 on 2025-06-18 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0004_alter_equipamento_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='em_manutencao',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('descricao', models.TextField()),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='academico.equipamento')),
            ],
        ),
    ]
