# Generated by Django 5.2.3 on 2025-06-18 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0005_equipamento_em_manutencao_manutencao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manutencao',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='equipamento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manutencao', to='academico.equipamento'),
        ),
    ]
