# Generated by Django 5.2.3 on 2025-06-18 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0006_alter_manutencao_data_alter_manutencao_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='data_alugado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='status',
            field=models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('INDISPONIVEL', 'Indisponível'), ('ALUGADO', 'Alugado')], default='DISPONIVEL', max_length=20),
        ),
    ]
