# Generated by Django 5.2.3 on 2025-06-18 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0007_equipamento_data_alugado_alter_equipamento_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='equipamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.equipamento'),
        ),
    ]
