# Generated by Django 5.2.3 on 2025-07-07 14:55

import django.db.models.deletion
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('INDISPONIVEL', 'Indisponível'), ('ALUGADO', 'Alugado')], default='DISPONIVEL', max_length=20)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('fabricante', models.CharField(blank=True, max_length=100, null=True)),
                ('em_manutencao', models.BooleanField(default=False)),
                ('data_alugado', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('equipamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manutencao', to='locadora.equipamento')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('foto', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='fotos/equipamentos', variations={'medium': (300, 300), 'thumb': (150, 150)})),
                ('data_nascimento', models.DateField()),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('NB', 'Não-binário'), ('O', 'Outro')], max_length=2)),
                ('estado_civil', models.CharField(choices=[('S', 'Solteiro'), ('C', 'Casado'), ('D', 'Divorciado'), ('V', 'Viúvo')], max_length=30)),
                ('escolaridade', models.CharField(choices=[('fun', 'Fundamental'), ('med', 'Médio'), ('sup', 'Superior'), ('pos', 'Pós-graduação'), ('mes', 'Mestrado'), ('dou', 'Doutorado')], max_length=50)),
                ('ativo', models.BooleanField(default=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('rua', models.CharField(blank=True, max_length=100, null=True)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('equipamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locadora.equipamento')),
            ],
        ),
    ]
