# Generated by Django 5.2.3 on 2025-07-08 03:03

import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='foto',
        ),
        migrations.AddField(
            model_name='equipamento',
            name='foto',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='fotos/equipamentos', variations={'medium': (300, 300), 'thumb': (150, 150)}),
        ),
    ]
